### ISSUE TITLE
About rotation formula at the bottom of README.md

### ISSUE THREAD

**Issue by ghost** [ClementPinard/FlowNetPytorch#103]
At the bottom of README.md, there is a formula for ratate function which I think has a little typo. I suppose the correct formula is:
```
rotate: x,y,theta ->  (x*cos(theta) - x*sin(theta), y*cos(theta) + x*sin(theta))
```
, where the second element of output is `y*cos(theta) + x*sin(theta)` rather than `y*cos(theta),  x*sin(theta)`.

Finally, thank you so much for this nice implementation of flownet !

**Comment by ClementPinard** [comment]
Hello, see how it has corrected here  #99 
so the whole formula needs to be updated, I'll try to fix this in the future.
