### ISSUE TITLE
Error when testing pre-trained Flownets netowrk

### ISSUE THREAD

**Issue by sparviero19** [ClementPinard/FlowNetPytorch#11]
Hi, 
I am trying to run the flownets model and predict the optical flow given a pair of images from the KITTI dataset. I downloaded the pretrained model, but when I run the prediction step it gives me the following error: 

`
Traceback (most recent call last):
  File "flownet_test.py", line 74, in <module>
    output = model(Variable(torch.from_numpy(x_test)))
  File "torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "FlowNetPyTorch.py", line 95, in forward
    concat5 = torch.cat((out_conv5, out_deconv5, flow6_up), 1)
  File "python3.5/site-packages/torch/autograd/variable.py", line 897, in cat
    return Concat.apply(dim, *iterable)
  File "/python3.5/site-packages/torch/autograd/_functions/tensor.py", line 317, in forward
    return torch.cat(inputs, dim)
RuntimeError: inconsistent tensor sizes at /pytorch/torch/lib/TH/generic/THTensorMath.c:2709`

When I print the size of out_conv5, out_deconv5 and flow6_up it gives me:

`torch.Size([1, 512, 3, 10])
torch.Size([1, 512, 4, 10])
torch.Size([1, 2, 4, 10])`

The input tensor has the following dimension: 
`(1, 6, 94, 300)`

Any idea about how to fix this?
Thanks

**Comment by ClementPinard** [comment]
You need to make height and width divisible by 64 as size are halved and then doubled 6 times (i.e. size*2^-5 needs to be divisible by 2). For such a tiny picture, it's going to be a problem as it will result in heavy cropping or warping but if you are reading KITTI images, i suggest you to try to resize images to 832x256, which is kind of the same ratio (although not the exact same)

You can run FlowNet on this image and then to get the original flow back multiply xflow by `original_width/832` and yflow by `original_height/256`

If you cannot work with anything else than tiny images, you can modify FlowNetS architecture to crop upsampled feature maps to match higher order feature maps.

Essentially you can modify FlowNetS with this snippet in forward function :

```python
flow6       = self.predict_flow6(out_conv6)
flow6_up    = self.upsampled_flow6_to_5(flow6)[:, :, :out_conv5.size(2), :out_conv5.size(3)]
out_deconv5 = self.deconv5(out_conv6)[:, :, :out_conv5.size(2), :out_conv5.size(3)]
        
concat5 = torch.cat((out_conv5,out_deconv5,flow6_up),1)
flow5       = self.predict_flow5(concat5)
flow5_up    = self.upsampled_flow5_to_4(flow5)[:, :, :out_conv4.size(2), :out_conv4.size(3)]
out_deconv4 = self.deconv4(concat5)[:, :, :out_conv4.size(2), :out_conv4.size(3)]
        
concat4 = torch.cat((out_conv4,out_deconv4,flow5_up),1)
flow4       = self.predict_flow4(concat4)
flow4_up    = self.upsampled_flow4_to_3(flow4)[:, :, :out_conv3.size(2), :out_conv3.size(3)]
out_deconv3 = self.deconv3(concat4)[:, :, :out_conv3.size(2), :out_conv3.size(3)]

concat3 = torch.cat((out_conv3,out_deconv3,flow4_up),1)
flow3       = self.predict_flow3(concat3)
flow3_up    = self.upsampled_flow3_to_2(flow3)[:, :, :out_conv2.size(2), :out_conv2.size(3)]
out_deconv2 = self.deconv2(concat3)[:, :, :out_conv2.size(2), :out_conv2.size(3)]

```

**Comment by sparviero19** [comment]
Thanks you for your assistance, that solved my problem
