### ISSUE TITLE
torch.load('flownets_pytorch.pth') doesn't work

### ISSUE THREAD

**Issue by gauravpandeyamu** [ClementPinard/FlowNetPytorch#2]
I downloaded the pretrained flownet model for pytorch. However, when I execute torch.load('flownets_pytorch.pth'), I get InvalidHeaderError.
I was wondering if I am loading it incorrectly.

**Comment by ClementPinard** [comment]
hello, unfortanately, the model loading works with me, when doing only
```python
import torch
torch.load('flownets_pytorch.pth')
```

I did a fresh reinstall from pip (2.7 and 3.5) and got no problem either.
Maybe try to reinstall it ?
what do other pretrained models as in https://github.com/pytorch/vision/tree/master/torchvision/models give ?

**Comment by gauravpandeyamu** [comment]
Thanks.  I just wanted to confirm that I was loading it correctly.  The
issue can be closed.  The problem is probably with my pytorch libraries.  I
will update them and check.

**Comment by SaltwaterLHL** [comment]
I downloaded the model in the pytorch folder,but I cann't open the tar.
#tar -xf ***.tar
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
