### ISSUE TITLE
When will release the implement of FlowNetC？

### ISSUE THREAD

**Issue by flyingmoth** [ClementPinard/FlowNetPytorch#21]

**Comment by ClementPinard** [comment]
FlowNetC requires a specific module to be implemented, but it may change in the future
see here :
https://github.com/pytorch/pytorch/issues/4073
also, you might want to take a look at NVDIA's flownet2, which features FlowNetC:
https://github.com/NVIDIA/flownet2-pytorch/blob/master/networks/FlowNetC.py
