### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by xin-xinhanggao** [ClementPinard/FlowNetPytorch#32]
It seems that pretrained model flownets_EPE1.951.pth.tar can not be uncompressed correctly.

**Comment by ClementPinard** [comment]
It is not compressed. You can feed it directly to the script.

The reason why `.tar`is added to the filename is simply to match official routines such as there : https://github.com/pytorch/examples/blob/master/imagenet/main.py#L267

But I agree that tar naming can be confusing as ubuntu (or any linux with a particular desktop environment) will try to untar it while it can't.
