### ISSUE TITLE
Sintel

### ISSUE THREAD

**Issue by bkvie** [ClementPinard/FlowNetPytorch#33]
Did you benchmark on Sintel? The official repository puts the files into subfiles alley, bamboo etc ... 
Either I am not using it correctly or the mpisintel.py loader doesn't take that into account. Are you extracting all images or should I rewrite the mpisintel.py file to open multiple folders?

**Comment by ClementPinard** [comment]
No benchmark on sintel yet. I'll take a look since KITTI is not completed with a fully working finetuning

**Comment by ClementPinard** [comment]
MPI sintel loader is now fully working. I am currently running a training, and visualization seems good too. Update your repo et let me know how it works for you !

Note : the data folder in CLI must be something like `/path/to/MPI-Sintel/training` while before it was only `/path/to/MPI-Sintel` don't forget to change it !
