### ISSUE TITLE
Reading/parsing of image pairs and flow fields

### ISSUE THREAD

**Issue by avisekiit** [ClementPinard/FlowNetPytorch#37]
Hi,
Thanks for sharing the code. I was not able to locate where you have actually read the image pairs and .flo file for a given image pair. Can you please point me to the code part where such reading of images and parsing of the .flo file is done.

Thanks,
Avisek

**Comment by ClementPinard** [comment]
Hello, for the .flo files, it's located [here](https://github.com/ClementPinard/FlowNetPytorch/blob/master/datasets/listdataset.py#L8)

For the PNG files in kitti, it's [here](https://github.com/ClementPinard/FlowNetPytorch/blob/master/datasets/KITTI.py#L18)
