### ISSUE TITLE
ImportError: /home/dell/.conda/envs/py3/lib/python3.6/site-packages/spatial_correlation_sampler_backend.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationESs

### ISSUE THREAD

**Issue by changshuangzhao** [ClementPinard/FlowNetPytorch#40]
After the compilation is successful, the operation is wrong.

`Traceback (most recent call last):
  File "/home/dell/device/FlowNetPytorch-master/models/util.py", line 3, in <module>
    from spatial_correlation_sampler import spatial_correlation_sample
  File "/home/dell/.conda/envs/py3/lib/python3.6/site-packages/spatial_correlation_sampler/__init__.py", line 1, in <module>
    from .spatial_correlation_sampler import SpatialCorrelationSampler, SpatialCorrelationSamplerFunction, spatial_correlation_sample
  File "/home/dell/.conda/envs/py3/lib/python3.6/site-packages/spatial_correlation_sampler/spatial_correlation_sampler.py", line 6, in <module>
    import spatial_correlation_sampler_backend as correlation
ImportError: /home/dell/.conda/envs/py3/lib/python3.6/site-packages/spatial_correlation_sampler_backend.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationESs
`

**Comment by ClementPinard** [comment]
What is your CUDA version ? And what is the CUDA version of your pytorch binary ?

**Comment by changshuangzhao** [comment]
Cuda compilation tools, release 8.0, V8.0.61
I can't run the correlation test script, The same error occurred

**Comment by changshuangzhao** [comment]
After pytorch is reinstalled, it can be run.Tank you !

**Comment by ClementPinard** [comment]
you're welcome :+1: 
What was your pytorch version before ? It is known not to work with pytorch 0.4.0 and lower versions.
