### ISSUE TITLE
Why is this error occurring while running? RuntimeError: sizes must be non-negative (THCTensor_resizeNd at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCTensor.cpp:108)

### ISSUE THREAD

**Issue by changshuangzhao** [ClementPinard/FlowNetPytorch#47]
My input is as follows:
a = t.ones(1, 2, 3, 4).float()
b = t.arange(-12, 12).view(1, 2, 3, 4).float()

cpu can be used, but gpu has error. RuntimeError: sizes must be non-negative (THCTensor_resizeNd at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCTensor.cpp:108)

**Comment by ClementPinard** [comment]
Ok, I guess you are using FlowNetC with my correlation module.

This is a known bug, You can see more info here : ClementPinard/Pytorch-Correlation-extension/issues/6

I'll file a patch soon, but you can already do it as it is pretty simple, the problems is occuring when creating the output tensor, and depending on your compiler, there's a confusion between signed and unsigned I guess.
