### ISSUE TITLE
Models cannot be  decompression

### ISSUE THREAD

**Issue by SaltwaterLHL** [ClementPinard/FlowNetPytorch#53]
I downloaded the model in the pytorch path,but I can not open the tar file.
#tar -xvf ***.tar
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

**Comment by ClementPinard** [comment]
It's not a tar file, it's directly a pth file, so you just have to give it to pretrained argument like that.

As to why we append the tar extension then, it's to match the official imagenet example here : https://github.com/pytorch/examples/blob/master/imagenet/main.py#L350

I think the main idea is to denote the fact that the file is a full dictionnary contained in one file, the same way a tar file is a bunch of files concatenated together.

A tar file is not a compressed file,however the gz or xz is, hence the .tar.gz or .tar.xz that you get at the end of compressed files.

**Comment by SaltwaterLHL** [comment]
Thanks！
I have one questions that why the result of the pretrained model is not the paper result？






At 2019-01-03 21:10:01, "Clément Pinard" <notifications@github.com> wrote:


It's not a tar file, it's directly a pth file, so you just have to give it to pretrained argument like that.

As to why we append the tar extension then, it's to match the official imagenet example here : https://github.com/pytorch/examples/blob/master/imagenet/main.py#L350

I think the main idea is to denote the fact that the file is a full dictionnary contained in one file, the same way a tar file is a bunch of files concatenated together.

A tar file is not a compressed file,however the gz or xz is, hence the .tar.gz or .tar.xz that you get at the end of compressed files.

**Comment by ClementPinard** [comment]
The training is not the exact same.

I could try to figure out what they did exactly, because the code source is available, but the data augmentation layers are not well documented and the original code's README event states that there is no guarantee the code will converge to the same result.

For these reasons, and because the results were quite good in this repo I thought it was not worth working on reimplementing their data augmentation code with the exact same hyper parameters.

A nice follow up of this, is the article of FlowNet2 from the same team that states that they could not get the same result as FlowNetS and FlowNetC : https://arxiv.org/pdf/1612.01925.pdf (section 3.2), illustrating how hard replicating perfectly the experiment is.

**Comment by SaltwaterLHL** [comment]
Sorry，maybe my problem is described incorrectly. 


In the FlowNet paper, the FlowNetC test result in Sintel  is 
but I use your model and the trained caffe model weight to test the result (without retraining) in Sintel is not the same as what the paper shows.


Why is so? 






At 2019-01-04 16:43:28, "Clément Pinard" <notifications@github.com> wrote:


The training is not the exact same.

I could try to figure out what they did exactly, because the code source is available, but the data augmentation layers are not well documented and the original code's README event states that there is no guarantee the code will converge to the same result.

For these reasons, and because the results were quite good in this repo I thought it was not worth working on reimplementing their data augmentation code with the exact same hyper parameters.

A nice follow up of this, is the article of FlowNet2 from the same team that states that they could not get the same result as FlowNetS and FlowNetC : https://arxiv.org/pdf/1612.01925.pdf (section 3.2), illustrating how hard replicating perfectly the experiment is.

**Comment by ClementPinard** [comment]
The Caffe model accepts BGR input and not RGB. Normally, it should not be a huge problem since the optical flow problem is the same with RGB and BGR, but it will have different results.
So my guess would be that.

**Comment by SaltwaterLHL** [comment]
Thanks!
I have another questions about the mean value in Caffe code not the same as your code.Does it have an effect on the results ?
and the parameters(mean_scale and output_scale)  have not value  in the mean_layer .cpp.
How did you deal with it?









At 2019-01-04 19:05:12, "Clément Pinard" <notifications@github.com> wrote:


The Caffe model accepts BGR input and not RGB. Normally, it should not be a huge problem since the optical flow problem is the same with RGB and BGR, but it will have different results.
So my guess would be that.
