### ISSUE TITLE
name 'spatial_correlation_sample' is not defined

### ISSUE THREAD

**Issue by lovemmmax** [ClementPinard/FlowNetPytorch#55]
When I trained the FlownetC, it occurs the error of "name 'spatial_correlation_sample' is not defined".
I was wondering where can I found the definition?

**Comment by ClementPinard** [comment]
You need to install the python module for correlation sampler : 

```
pip install spatial-correlation-sampler>=0.0.8
```

If you have trouble installing this module, you can go to the github repo : https://github.com/ClementPinard/Pytorch-Correlation-extension
