### ISSUE TITLE
flowToRgb

### ISSUE THREAD

**Issue by 1292765944** [ClementPinard/FlowNetPytorch#56]
How to understand the code? and is it different from the code in Sintel used by FlowNet?

**Comment by ClementPinard** [comment]
It's probably different, although based on the same idea. No foamlized method has been enforced so the color choices conventions vary.

The main idea is to take a white YUV picture (so with U and V to zero) and put flow values on U and V.
See this [article for](https://en.wikipedia.org/wiki/YUV) more info about YUV (and especially [this paragraph](https://en.wikipedia.org/wiki/YUV#Conversion_to/from_RGB)

as such we convert the 3d vector [1FuFv] to [RGB] using the matrix

```
[[R]   [[1  0    0.5][[Y]
 [G]  = [1  0.5 -0.5] [U]
 [B]]   [1 -0.5  0.5] [V]]
```

**Comment by 1292765944** [comment]
Ok, I see. Your code already produces nice flowToRgb images and I'll follow your code. Thank you!
