### ISSUE TITLE
Error in norm dimension

### ISSUE THREAD

**Issue by emited** [ClementPinard/FlowNetPytorch#6]
Hi,
This could be me, but when you calculate your EPE, isn't the dimension you want to calculate the norm on 1, instead of 2, since your inputs are of size (size of batch, 2, x_size, y_size)?

def EPE(input_flow, target_flow):
    return torch.norm(target_flow-input_flow,2,2)

**Comment by ClementPinard** [comment]
Hello, thanks a lot for your insight, you are indeed correct. I pushed it and it should be solved now.

Clément
