### ISSUE TITLE
multiply by args.div_flow

### ISSUE THREAD

**Issue by bkvie** [ClementPinard/FlowNetPytorch#61]
https://github.com/ClementPinard/FlowNetPytorch/blob/c37a8dba6e1b3832a93384d25d196e0bacff545c/run_inference.py#L113

Hi is this supposed to be raw output or .flo output? Should this be multiplied by args.div_flow?

**Comment by ClementPinard** [comment]
Yes you're right, it's better to multiply it by args.div_flow to have the real optical flow instead of just raw network output

**Comment by bkvie** [comment]
Can I do a pull request?

**Comment by ClementPinard** [comment]
Please do , thanks !
