### ISSUE TITLE
squeeze()

### ISSUE THREAD

**Issue by bkvie** [ClementPinard/FlowNetPytorch#63]
https://github.com/ClementPinard/FlowNetPytorch/blob/d62f7d93244c21608f34c62704cd4a9c6dcd845d/run_inference.py#L113

 to_save = (args.div_flow*flow_output).squeeze().cpu().numpy().transpose(1,2,0)

then it would be .flo format. any use in saving with batch dimension? if we were to load this file for comparison we would unsqueeze(0) anyway?

**Comment by bkvie** [comment]
currently this will throw an error

**Comment by ClementPinard** [comment]
Yes, sorry, Wrote it without testing it...

Indeed it should be `flow_output[0]` instead of `flow_output`

**Comment by ClementPinard** [comment]
After a re-check
In fact the [0] is already done in the zip function. Are you sure this throws an error ? Tested fine on my side.

**Comment by bkvie** [comment]
Is it? did I edit something on my model that would cause different output? which line are you referring to?

**Comment by ClementPinard** [comment]
https://github.com/ClementPinard/FlowNetPytorch/blob/d62f7d93244c21608f34c62704cd4a9c6dcd845d/run_inference.py#L105

We iterate through output, which then makes the first dimension disappear
