### ISSUE TITLE
Citation info

### ISSUE THREAD

**Issue by SRSH88** [ClementPinard/FlowNetPytorch#69]
Hello,
Thank you for sharing your work. 
I used your implementation of FlowNet and the pre-trained weights in my work. I was wondering what is your preferred way of citing this work?

**Comment by ClementPinard** [comment]
Hello,

thanks for considering citing this work !
I would not make an academic citation, the original author's one is enough as I didn't implement something new. However, you can indicate this repo using a footnote.

Another solution would be to mention this repo in the aknowledgement.

Clément
