### ISSUE TITLE
spatial-correlation-sampler

### ISSUE THREAD

**Issue by ALIEDTECH** [ClementPinard/FlowNetPytorch#71]
Hi, I got this error message when i want to install "spatial-correlation-sampler"

"Could not find a version that satisfies the requirement torch>=1.0.1 (from spatial-correlation-sampler) (from versions: 0.1.2, 0.1.2.post1)
No matching distribution found for torch>=1.0.1 (from spatial-correlation-sampler)"

My pytorch version:

# Name                    Version                   Build  Channel
pytorch                   0.4.1           py37_cuda92_cudnn7he774522_1  [cuda92]  pytorch
pytorch-nightly           1.1.0.dev20190616 py3.7_cuda100_cudnn7_0    pytorch
torchvision               0.2.2.post3              pypi_0    pypi

Thanks.

**Comment by ClementPinard** [comment]
Your version of pytorch is not up to date enough.
You need to upgrade it to 1.0.1

**Comment by ALIEDTECH** [comment]
I upgrade it to 1.0.1 but when I execute the command : 'pip install spatial-correlation-sampler ' 
I got this error:

 1 error detected in the compilation of "C:/Users/ALI/AppData/Local/Temp/tmpxft_00002760_00000000-8_correlation_cuda_kernel.cpp4.ii".
  correlation_cuda_kernel.cu
  error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\bin\\nvcc.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for spatial-correlation-sampler

##############################################################
    1 error detected in the compilation of "C:/Users/ALI/AppData/Local/Temp/tmpxft_000013a0_00000000-8_correlation_cuda_kernel.cpp4.ii".
    correlation_cuda_kernel.cu
    error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\bin\\nvcc.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command "'c:\users\ali\appdata\local\continuum\anaconda3\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\ALI\\AppData\\Local\\Temp\\pip-install-1ils9jm2\\spatial-correlation-sampler\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ALI\AppData\Local\Temp\pip-record-3fz3ihwa\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ALI\AppData\Local\Temp\pip-install-1ils9jm2\spatial-correlation-sampler\

**Comment by ClementPinard** [comment]
Unfortunately I never tested it on windows so it might just not be compatible.

To have a more thorough error trace you can try to install it from source with

`python setup.py install`

From this repo.
