### ISSUE TITLE
[newbie question] importing main.py in jupyter dataloader issue ''tuple not callable"

### ISSUE THREAD

**Issue by jeffbaena** [ClementPinard/FlowNetPytorch#72]
Dear Clement,
 I am importing your main.py script into jupyter, this is because I would like to change some training parameters. I (think) I have carrefully imported your main.py code to jupyter, by hardcoding the varibles input with args.####.

The problem is that when I call the function "train" called I get a 'tuple is not callable exception', but the dataloader seems to be a function and to be iterable.
Attached is the error I get, it is in the function __getitem__ .

I am having a hard time trying to debug this, did you by any chance faced a similar problem? Could it be a jupyter issue? Do you have some hints?

Regards,
Stefano

---------------------------------------------------------------------------
```
TypeError                                 Traceback (most recent call last)
<ipython-input-52-b5cc64e793e7> in <module>()
      3 
      4     # train for one epoch
----> 5     train_loss, train_EPE = train(train_loader, model, optimizer, epoch, train_writer)
      6     train_writer.add_scalar('mean EPE', train_EPE, epoch)
      7 

<ipython-input-34-3a741b5449d7> in train(train_loader, model, optimizer, epoch, train_writer)
     13     end = time.time()
     14 
---> 15     for i, (input, target) in enumerate(train_loader):
     16         # measure data loading time
     17         data_time.update(time.time() - end)

~/.conda/envs/FNC_env_p35/lib/python3.5/site-packages/torch/utils/data/dataloader.py in __next__(self)
    558         if self.num_workers == 0:  # same-process loading
    559             indices = next(self.sample_iter)  # may raise StopIteration
--> 560             batch = self.collate_fn([self.dataset[i] for i in indices])
    561             if self.pin_memory:
    562                 batch = _utils.pin_memory.pin_memory_batch(batch)

~/.conda/envs/FNC_env_p35/lib/python3.5/site-packages/torch/utils/data/dataloader.py in <listcomp>(.0)
    558         if self.num_workers == 0:  # same-process loading
    559             indices = next(self.sample_iter)  # may raise StopIteration
--> 560             batch = self.collate_fn([self.dataset[i] for i in indices])
    561             if self.pin_memory:
    562                 batch = _utils.pin_memory.pin_memory_batch(batch)

/FlowNetPytorch_py3/FlowNetPytorch/datasets/listdataset.py in __getitem__(self, index)
     45             inputs[1] = self.transform(inputs[1])
     46         if self.target_transform is not None:
---> 47             target = self.target_transform(target)
     48         return inputs, target
     49 

TypeError: 'tuple' object is not callable
```

**Comment by jeffbaena** [comment]
Sorry for the probably dull question, I found a typo in my code when defining "target_transform" I was fooled because of the nested code.

**Comment by ClementPinard** [comment]
not sure how you actually call the function train, since it needs some defined variables before. I suppose you hardcoded the corresponding code in the main() function.

Anyway, indeed when defining the dataset, you need to provide functions as "transform" parameters, that will return an image in the case of target_transform.

the corresponding code in the main function is located at https://github.com/ClementPinard/FlowNetPytorch/blob/master/main.py#L117

**Comment by jeffbaena** [comment]
For reference:
https://stackoverflow.com/questions/54431671/pytorch-dataloader-list-is-not-callable-error-when-enumerating
