### ISSUE TITLE
CONV6_1 layer existence query 

### ISSUE THREAD

**Issue by mukulkhanna** [ClementPinard/FlowNetPytorch#74]
Hi, thank you so much for the code!

I was going through the [paper](https://arxiv.org/pdf/1504.06852.pdf) and trying to understand the implementation using your code when I noticed that the last layer before the refinement layer is the `conv6` operation (512c -> 1024c)
![image](https://user-images.githubusercontent.com/24846546/61425625-1f008780-a935-11e9-98eb-db586e37a8fc.png)

In the refinement network, the first deconv operation (`deconv5`) happens on the ouput of the `conv6` layer. 
![image](https://user-images.githubusercontent.com/24846546/61425693-5d964200-a935-11e9-9f55-8bcd6ff94411.png)

But in your [code](https://github.com/ClementPinard/FlowNetPytorch/blob/361c3d5a6a781f6f4fc172d3882c139ee2d3d0e8/models/FlowNetC.py#L29), I see that there is a `conv6_1` operation on the output of the `conv6`.

```
out_conv6 = self.conv6_1(self.conv6(out_conv5))
```
where

```
self.conv6_1 = conv(self.batchNorm,1024, 1024)
```

It doesn't seem consistent with the paper (diagram at least) as I can't see a layer similar to `conv6_1` that takes in 1024c and outputs 1024c.

and similarly for this line ->
```
flow6 = self.predict_flow6(out_conv6)
```
The diagram shows that the first flow calculated is the `flow5` one.

Am I missing something? Please let me know, thanks.

**Comment by mukulkhanna** [comment]
Also, the diagram shows a kernel-size of 5x5 for the flow prediction in the refinement network. You have used a 3x3 kernel for the `predict_flow` method's conv layer [here](https://github.com/ClementPinard/FlowNetPytorch/blob/361c3d5a6a781f6f4fc172d3882c139ee2d3d0e8/models/util.py#L29).

![image](https://user-images.githubusercontent.com/24846546/61426739-0d20e380-a939-11e9-9ddb-e8ce3fbbb2b6.png)

**Comment by ClementPinard** [comment]
yes, the diagram is not consistent with their released code and pretrained network.

I preferred to match their implementation rather than their description is the paper.
See [here](https://lmb.informatik.uni-freiburg.de/resources/software.php) (in the post name "Disp- and FlowNet: Full code for testing and training networks") for their original caffe implementation.

**Comment by mukulkhanna** [comment]
Oh, thanks for the clarification!
