### ISSUE TITLE
Upsampling output?

### ISSUE THREAD

**Issue by sabrinazuraimi** [ClementPinard/FlowNetPytorch#75]
Hi, I'm trying to use the output of the network to move a few certain points(e.g: at pixel 441) however the output of the network is 1/16 of the input size.

My question is it possible to upsample/deconvolve the output so that I get a flow map that is the same size as the input image? (Or is there any other way to see how an exact pixel moved in the downsampled flow map?)

**Comment by ClementPinard** [comment]
Yes of course you can!

You might want to see the torch.nn.functional.interpolate function that will get you sorted out.

https://pytorch.org/docs/stable/nn.functional.html#interpolate
