### ISSUE TITLE
what's the path module?  "from path import Path" ?

### ISSUE THREAD

**Issue by wikiwen** [ClementPinard/FlowNetPytorch#76]
There is "from path import Path" in run_inference.py, but I can't install it by pip or conda. It's also not a built-in module in python3.

**Comment by wikiwen** [comment]
I install successfully by using "pip install path.py"

**Comment by kkew3** [comment]
Wow good to know. My initial guess was `pathlib` ... It would be great if these dependencies like `scipy` and `path.py` could be added to `requirements.txt`.

**Comment by ClementPinard** [comment]
Sorry about that, thought it was in the requirements.txt !

I'll add it, along with a mention in the README
