### ISSUE TITLE
questions about multiscaleloss

### ISSUE THREAD

**Issue by nsknsl** [ClementPinard/FlowNetPytorch#8]
In the code [here](https://github.com/ClementPinard/FlowNetPytorch/blob/607f99f46be3eccbd9b07c73848a68bc12156392/multiscaleloss.py#L63)
But I did not find this in the paper, could me please tell me ? Thanks.

**Comment by ClementPinard** [comment]
The paper only qrites about weighted loss for each scale. However, when looking at [their original](https://lmb.informatik.uni-freiburg.de/resources/binaries/dispflownet/dispflownet-release-1.2.tar.gz) code in caffe, you can see the very weights in the file train.prototxt
