### ISSUE TITLE
Normalization order

### ISSUE THREAD

**Issue by icam0** [ClementPinard/FlowNetPytorch#80]
A small detail; when training the network you normalize the images using the values in BGR order while the images are loaded in RGB order. I don't expect this to make a massive difference but just for consistency, it may be nice to either load the images in BGR order (to allow consistency with pretrained caffe model) or swap the normalization order.

https://github.com/ClementPinard/FlowNetPytorch/blob/master/main.py#L115

**Comment by ClementPinard** [comment]
Thanks for the issue, fixed
