### ISSUE TITLE
How to apply random rotation function to occlusion mask?

### ISSUE THREAD

**Issue by CXMANDTXW** [ClementPinard/FlowNetPytorch#83]
Thank you very much for your excellent work, which has provided a lot of convenience in my research.

I designed a model using occlusion label in optical flow dataset.Other data augmentation functions are very convenient to apply to the occlusion mask, but I have no idea about the random rotation function.I really hope to get your help.

**Comment by ClementPinard** [comment]
How do you define occlusion label ? Are they the pixels which are visible in first image, but not in second image ? Is it the opposite ?

If it's the first case, I don't think it's anymore complicated than just applying the occlusion mask the same transformation as the first image.

**Comment by CXMANDTXW** [comment]
sorry for late reply.
occlusion label are defined as you said, and actually I have tried to apply the occlusion mask the same transformation as the first image, but the result was bad.
![截图epe](https://user-images.githubusercontent.com/22285070/85925599-fb2b1d00-b8cb-11ea-9792-d61e52baa258.png)
![test](https://user-images.githubusercontent.com/22285070/85925602-02eac180-b8cc-11ea-86bf-3e771ad53476.png)
As shown in the picture, the model with rotation enhancement did not decline for a long time before training.
In my opinion, after using the rotation operation, because the rotation angles of the first frame and the second frame are different, the original non occluded pixels in the first frame may become occluded pixels, but the occlusion label does not handle it.
