### ISSUE TITLE
Real-time inference?

### ISSUE THREAD

**Issue by FedericoVasile1** [ClementPinard/FlowNetPytorch#84]
Hi, I congrats for your work.
I would like to know whether at inference time is it possible to use this model as part of a framework that performs the online action detection task? (i.e. let's suppose I have an input stream video, is the model able to compute optical-flow features as the frames arrive, with real-time speed ?)

Thank you!

**Comment by ClementPinard** [comment]
as usual, depends on your hardware

FlowNetS and FlownNetC are not really designed with speed in mind but can be used in this context with small enough images.

Back in 2016, I remeber having been able to run a webcam demo with a gaming laptop at 10fps.

What you can do though is to try more up to date works (as this repo now mainly serves as a basis for study) like e.g. LiteFlowNet : https://github.com/sniklaus/pytorch-liteflownet (it uses pytorch as well)

Or you can simply start from this repo to train lighter networks directly by just changing the network architecture.

Clément
