### ISSUE TITLE
Unable to extract pre-trained model

### ISSUE THREAD

**Issue by that-that-guy** [ClementPinard/FlowNetPytorch#87]
When I try to extract flownetc_EPE1.766.tar, I get the following error: 

`tar: This does not look like a tar archive`
`tar: Skipping to next header`
`tar: Exiting with failure status due to previous errors`

I got the file from [this](https://drive.google.com/drive/folders/16eo3p9dO_vmssxRoZCmWkTpNjKRzJzn5) linked google drive. Can you confirm if the file is working or not?

**Comment by ClementPinard** [comment]
the file is directly the weights, you don't have to extract. I followed the 2017 convention, nowadayw it would be called "flownetc_EPE1.766.pth" to avoid confusion like this one. The rationale behind the "tar" naming is that the same way the goal of tar is to concatenate files (the gz part is to compress the tar file), the wieghts file is the different weights simply concatenated with each other.
