### ISSUE TITLE
Data Augmentation

### ISSUE THREAD

**Issue by Johswald** [ClementPinard/FlowNetPytorch#9]
Hey!

Ich checked your data augmentation. In random rotate there is 

```python
#flow vectors must be rotated too! careful about Y flow which is upside down
        target_=np.array(target, copy=True)
        target[:,:,0] = np.cos(angle1_rad)*target_[:,:,0] + np.sin(angle1_rad)*target_[:,:,1]
        target[:,:,1] = -np.sin(angle1_rad)*target_[:,:,0] + np.cos(angle1_rad)*target_[:,:,1]
```
but in RandomCropRotate it is

```python
#flow vectors must be rotated too!
        target_=np.array(target, copy=True)
        target[:,:,0] = np.cos(angle1_rad)*target_[:,:,0] - np.sin(angle1_rad)*target_[:,:,1]
        target[:,:,1] = np.sin(angle1_rad)*target_[:,:,0] + np.cos(angle1_rad)*target_[:,:,1]
```

I guess the first one is correct?
Furthermore, if positive y flow is pointing downwards wouldn't you have to change the translation as well?
In RandomTranslate you do:

`target[:,:,1]+= th`

I guess if th is positive (you tranlsate upwards), your y flow would decrease?

What are your test scores on sintel (final, clean) or kitti?
Many thanks

**Comment by Johswald** [comment]
I think you were right with your translation.

image you have a 4x4 image

0000
0|000
0|100
0|000

1 has flow (1, -1):

000|0
001|0
000|0
0000

and you crop the two 3x3 images on the lower right and  upper left corner (as indicated)
then you end up with a translation of (1,1) 
(with your code, which is a bit confusing, (-1, -1) would make more sense)

the new flow of 1 has to be (2,0)
so 
target[:,:,1]+= th
and
target[:,:,o]+= tw
is correct. Right? :)

**Comment by ClementPinard** [comment]
Hello, thanks for your comment ! Unfortunately no test results on Sintel and KITTI. I lacked of time for running and then shifted to another [project](https://github.com/ClementPinard/DepthNet). This project may be a little outdated, and may need an update on its coding style and README presentation.

However, Random transfomrs have been checked.

I think the first rotation is the one used in the main and thus should be the correct one.

For `RandomTranslate`, the code is actually the other way around, you define your translation and then corp accordingly. And if you make a particular translation, cropping is done with the opposite translation, because the upper left corner of the crop rectangle is then set to (0,0)

**Comment by Johswald** [comment]
Hey! Thanks for your quick answer. Your new project looks cool, you might check:
[Depth from focus](https://arxiv.org/abs/1704.01085).
Another small thing, I couldn't find any upsampling after your last flow. Is that correct?
For every loss you downsample your target (should one also scale the flow accordingly)
but the last flow2 has not the original image size right? My (not finished) tensorflow implementation is not able to reach the ~3 epe in the test set so i am wondering what goes wrong.
Thanks!

**Comment by ClementPinard** [comment]
That is correct, original Caffe code did only flow maps of H/4,W/4. They justify it by the fact upsampling it more with convolutions is not better than a simple bicubic upsampling.

**Comment by ClementPinard** [comment]
You might want to look at the updated code now, it converges much better :)

**Comment by bkvie** [comment]
Hi,
any way to turn off data augmentation? I want to compare both methods (with/with out data pre-processing).

**Comment by ClementPinard** [comment]
You can just delete this line in main.py : https://github.com/ClementPinard/FlowNetPytorch/blob/master/main.py#L144
All data augmentation is comprised in co_transform routines
