### ISSUE TITLE
About import spatial_correlation_sample

### ISSUE THREAD

**Issue by zouzhiwei217** [ClementPinard/FlowNetPytorch#98]
Excuse me, is import spatial_correlation_sample the contents of the package to be installed?

**Comment by ClementPinard** [comment]
Yes
You only need it for FlowNetC though

**Comment by Vaishnavi-1712** [comment]
I want to implement FlowNetC, can you please let me know from where "spatial_correlation_sample" has to be imported

**Comment by ClementPinard** [comment]
Sorry, I though I had linked it in the README but it does not seem to be the case
https://github.com/ClementPinard/Pytorch-Correlation-extension
Norally you should be able to install it directly with pip
